create table derived_VDI(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
mapping_id number,
week_start_date date,
node_name varchar(20),
node_voltage number,
maximum number,
minimum number,
less_than_band number(4,2),
between_band number(4,2),
greater_than_band number(4,2),
less_than_band_inHrs number(5,2),
greater_than_band_inHrs number(5,2),
out_of_band_inHrs number(5,2),
VDI number(4,3),
constraints unique_derived_VDI unique(week_start_date,node_name),
constraints fk_derived_VDI foreign key(mapping_id) references mapping_table(id),
constraints pk_derived_VDI primary key(id)
)