create table derived_frequency(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
Date_key date check (date_key = trunc(date_key)) unique,
maximum number(4,2),
minimum number(4,2),
average number(4,2),
less_than_band number(4,2),
between_band number(4,2),
greater_than_band number(4,2),
out_of_band number(4,2),
out_of_band_inhrs number(4,2),
FDI number(4,2))
