create table derived_voltage
(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
date_key date,
mapping_id number,
node_scada_name varchar2(30),
node_name varchar2(20),
min number(3,0),
maximum number(3,0),
average number(3,0),
constraints unique_derived_volt unique(date_key,node_name),
constraints fk_derived_volt foreign key(mapping_id) references mapping_table(id),
constraints pk_derived_volt primary key(id)
)