create table raw_voltage(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    time_stamp date,
    node_scada_name varchar(15),
    voltage_value number(3),
    constraint pk_voltage primary key(id),
    constraint unique_voltage unique(time_stamp, station_name)
)