-- create table derivedFreq(
-- id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
-- Date_key date check (date_key = trunc(date_key)) unique,
-- maximum number(4,2),
-- minimum number(4,2),
-- average number(4,2),
-- less_than_band number(4,2),
-- between_band number(4,2),
-- greater_than_band number(4,2),
-- out_of_band number(4,2),
-- out_of_band_inhrs number(4,2),
-- FDI number(4,2))

-- select count(*),trunc(vt.time_stamp) date_key,max(mt.ID)ID ,vt.node_scada_name,min(mt.node_name)Node_name,min(vt.voltage_value) min,max(vt.voltage_value) max,avg(vt.voltage_value) avg
-- from mapping_table mt,voltage vt 
-- where mt.NODE_SCADA_NAME = vt.NODE_SCADA_NAME and vt.time_stamp between to_date('2019-07-22 00:00:00') and to_date('2019-07-23 23:59:00')
-- group by vt.node_scada_name,trunc(vt.time_stamp)
-- order by date_key,ID


